nodeLinker: node-modules

npmPublishRegistry: "https://registry.yarnpkg.com"

npmRegistryServer: "https://registry.npmmirror.com"

yarnPath: .yarn/releases/yarn-4.4.0.cjs

compressionLevel: mixed

enableTips: false
